import { BadRequestException, Body, Controller, Get, Headers, Logger, Param, Post, Query, Res } from '@nestjs/common';
import type { Response } from 'express';

import { AuditService } from '../../core/audit/audit.service.js';
import { RequiredScopes } from '../identity/auth.decorators.js';
import { AppealPerformanceDto, CalibratePerformanceDto, CreatePerformanceCycleDto, CreatePerformanceTemplateDto, FinalizePerformanceDto, SubmitPerformanceScoreDto } from './application/performance.dto.js';
import { PerformanceService } from './application/performance.service.js';

const ULID = /^[0-7][0-9A-HJKMNP-TV-Z]{25}$/; const KEY = /^[A-Za-z0-9._:-]{8,128}$/; const ETAG = /^"([1-9][0-9]*)"$/;

@Controller('performance')
export class PerformanceController {
  private readonly logger = new Logger(PerformanceController.name);
  constructor(private readonly performance: PerformanceService, private readonly audit: AuditService) {}
  @Post('templates') @RequiredScopes('erp:performance:admin')
  async createTemplate(@Headers('idempotency-key') key: string | undefined, @Body() body: CreatePerformanceTemplateDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.createTemplate(this.key(key), body); this.etag(response, result.template.version); await this.success('performance.template.create', 'performance_template', result.template.id, result.template.version, 'R2'); return result; }
  @Get('templates') @RequiredScopes('erp:performance:admin') async templates() { return { items: await this.performance.listTemplates() }; }
  @Post('cycles') @RequiredScopes('erp:performance:admin')
  async createCycle(@Headers('idempotency-key') key: string | undefined, @Body() body: CreatePerformanceCycleDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.createCycle(this.key(key), body); this.etag(response, result.cycle.version); await this.success('performance.cycle.create', 'performance_cycle', result.cycle.id, result.cycle.version, 'R2'); return result; }
  @Get('cycles') @RequiredScopes('erp:performance:read') async cycles() { return { items: await this.performance.listCycles() }; }
  @Post('cycles/:id/publish') @RequiredScopes('erp:performance:admin')
  async publish(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: unknown, @Res({ passthrough: true }) response: Response) { this.empty(body); const result = await this.performance.publishCycle(this.id(id), this.version(version), this.key(key)); this.etag(response, result.cycle.version); await this.success('performance.cycle.publish', 'performance_cycle', result.cycle.id, result.cycle.version, 'R2'); return result; }
  @Get('assignments/me') @RequiredScopes('erp:performance:self:read') async mine() { return { items: await this.performance.listMine() }; }
  @Get('assignments/team') @RequiredScopes('erp:performance:team:read') async team(@Query('cycleId') cycleId?: string) { return { items: await this.performance.listTeam(cycleId === undefined ? undefined : this.id(cycleId)) }; }
  @Get('assignments/calibration') @RequiredScopes('erp:performance:calibration:read') async calibration(@Query('cycleId') cycleId?: string) { return { items: await this.performance.listCalibration(cycleId === undefined ? undefined : this.id(cycleId)) }; }
  @Post('assignments/:id/self-review') @RequiredScopes('erp:performance:self:write') async self(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: SubmitPerformanceScoreDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.submitSelf(this.id(id), this.version(version), this.key(key), body); this.etag(response, result.assignment.version); await this.success('performance.assignment.self_review', 'performance_assignment', result.assignment.id, result.assignment.version, 'R2'); return result; }
  @Post('assignments/:id/manager-review') @RequiredScopes('erp:performance:manager:write') async manager(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: SubmitPerformanceScoreDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.submitManager(this.id(id), this.version(version), this.key(key), body); this.etag(response, result.assignment.version); await this.success('performance.assignment.manager_review', 'performance_assignment', result.assignment.id, result.assignment.version, 'R2'); return result; }
  @Post('assignments/:id/calibrate') @RequiredScopes('erp:performance:calibration:write') async calibrate(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: CalibratePerformanceDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.calibrate(this.id(id), this.version(version), this.key(key), body); this.etag(response, result.assignment.version); await this.success('performance.assignment.calibrate', 'performance_assignment', result.assignment.id, result.assignment.version, 'R2'); return result; }
  @Post('assignments/:id/confirm') @RequiredScopes('erp:performance:self:write') async confirm(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: unknown, @Res({ passthrough: true }) response: Response) { this.empty(body); const result = await this.performance.confirm(this.id(id), this.version(version), this.key(key)); this.etag(response, result.assignment.version); await this.success('performance.assignment.confirm', 'performance_assignment', result.assignment.id, result.assignment.version, 'R2'); return result; }
  @Post('assignments/:id/appeal') @RequiredScopes('erp:performance:self:write') async appeal(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: AppealPerformanceDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.appeal(this.id(id), this.version(version), this.key(key), body); this.etag(response, result.assignment.version); await this.success('performance.assignment.appeal', 'performance_assignment', result.assignment.id, result.assignment.version, 'R2'); return result; }
  @Post('assignments/:id/finalize') @RequiredScopes('erp:performance:finalize') async finalize(@Param('id') id: string, @Headers('if-match') version: string | undefined, @Headers('idempotency-key') key: string | undefined, @Body() body: FinalizePerformanceDto, @Res({ passthrough: true }) response: Response) { const result = await this.performance.finalize(this.id(id), this.version(version), this.key(key), body); this.etag(response, result.assignment.version); await this.success('performance.result.finalize', 'performance_assignment', result.assignment.id, result.assignment.version, 'R3'); return result; }
  @Get('payroll-snapshots/:cycleId') @RequiredScopes('erp:performance:payroll_snapshot:read') async snapshots(@Param('cycleId') cycleId: string) { return { items: await this.performance.payrollSnapshots(this.id(cycleId)) }; }
  private id(value: string) { if (!ULID.test(value)) throw new BadRequestException({ code: 'PERFORMANCE_ID_INVALID', message: '资源标识必须为严格 ULID' }); return value; }
  private key(value: string | undefined) { if (value === undefined || !KEY.test(value)) throw new BadRequestException({ code: 'IDEMPOTENCY_KEY_REQUIRED', message: '写接口必须提供 8–128 位白名单 Idempotency-Key' }); return value; }
  private version(value: string | undefined) { const match = ETAG.exec(value ?? ''); const parsed = Number(match?.[1]); if (match === null || !Number.isSafeInteger(parsed) || parsed >= Number.MAX_SAFE_INTEGER) throw new BadRequestException({ code: 'PERFORMANCE_IF_MATCH_REQUIRED', message: '写接口必须提供强 If-Match 版本' }); return parsed; }
  private empty(value: unknown) { if (value === undefined) return; if (typeof value !== 'object' || value === null || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype || Reflect.ownKeys(value).length !== 0) throw new BadRequestException({ code: 'PERFORMANCE_BODY_FORBIDDEN', message: '该操作不接受请求正文' }); }
  private etag(response: Response, version: number) { response.setHeader('ETag', `"${version}"`); }
  private async success(action: string, resourceType: string, resourceId: string, version: number, riskLevel: 'R2' | 'R3') { try { await this.audit.record({ action, resourceType, resourceId, riskLevel, outcome: 'success', metadata: { version } }); } catch { this.logger.error('PERFORMANCE_COMMITTED_AUDIT_WRITE_FAILED'); } }
}
