apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-api
  namespace: {{ include "gaoq-erp.targetNamespace" . }}
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.apiMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-worker
  namespace: {{ include "gaoq-erp.targetNamespace" . }}
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.workerMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-web
  namespace: {{ include "gaoq-erp.targetNamespace" . }}
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.podDisruptionBudget.webMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-website
  namespace: {{ include "gaoq-erp.targetNamespace" . }}
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: website
spec:
  minAvailable: {{ .Values.podDisruptionBudget.websiteMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: website
