apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-api
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-web
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaoq-erp.fullname" . }}-worker-metrics
  labels:
    {{- include "gaoq-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "gaoq-erp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: 9464
      targetPort: metrics
      protocol: TCP
